language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

install:
    pip install nose coveralls coverage
script:
    nosetests --with-coverage --cover-package=neat
after_success:
    coveralls
